name: arweave import

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

concurrency: 
  group: run-arweave-import-oneshot
  cancel-in-progress: false

jobs:
  run-arweave-import-oneshot:
    name: run-arweave-import-oneshot
    runs-on: ubuntu-latest
    environment: import
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: yarn install
      run: yarn install
    - name: install typescript
      run: npm install -g typescript
    - name: change directory
      run: cd ./cmd
    - name: compile
      run: tsc ./cmd/arweave.ts --esModuleInterop
    - name: list files
      run: ls ./cmd
    - name: run
      run: node ./cmd/arweave.js
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
